### ISSUE TITLE
Rethink PenaltyManager

### ISSUE THREAD

**Issue by N-Wouda** [N-Wouda/PyVRP#100]
Rather than having many classes depend on the `PenaltyManager` directly, we can ask the `PenaltyManager` for a value object that can provide the current load and time warp penalties.

**Comment by wouterkool** [comment]
And let's implement the `PenaltyManager` in Python while we're at it? :)

**Comment by wouterkool** [comment]
I have given this some thought. Using the penalties can be seen as using a proxy objective for the real objective (which has hard constraints), and this proxy objective changes during optimization as the penalties change. That makes the definition of `Individual.cost()` ambiguous and dependent on the state of the algorithm.

How about we make this explicit and define an `Objective` class (somewhat more general than Penalties) that takes an individual and returns the cost, and remove `Individual.cost` at all? The Objective class could also be used inside local search, providing the `twPenalty` and `loadPenalty` methods.

We can then implement the PenaltyManager class in Python and pass `PenaltyManager.get_objective()` (or perhaps `PenaltyManager.get_booster_objective()`) to `LocalSearch.run`.

The Objective class could also be used to define different objectives (e.g. taking into account waiting time) in the future, although this would require changes to the LocalSearch operators as well.

Note that the fitness computation in the `SubPopulation` depends on the cost, and it is rather dependent on subtle implementation details that the fitness is now recomputed correctly when the penalties change. I think we should somehow trigger the population explicitly when the Objective changes, or always pass the `Objective` as a parameter such that the implementation can detect itself when the objective changes.

**Comment by wouterkool** [comment]
Regarding the `SubPopulation` that depends on the cost... we could also choose to let the 'managed penalties' only apply to the local search to encourage resulting in feasbile solutions, but keep a fixed penalty (i.e. a 'static' relaxed objective) when computing cost for an individual in the population. This makes things less coupled as population no longer depends on changing penalties, but it may affect the performance as well.

**Comment by N-Wouda** [comment]
> How about we make this explicit and define an `Objective` class (somewhat more general than Penalties) that takes an individual and returns the cost, and remove `Individual.cost` at all? The Objective class could also be used inside local search, providing the `twPenalty` and `loadPenalty` methods.

I just returned to this issue to add my thoughts and reread the comments before writing them down. This is what I'm in favour of as well. I think I'd call this a `CostEvaluator` instead, which to me more clearly indicates that it's also about penalties and (delta) costs, not just about `Individual::cost` as we have it currently. We should then also rename `PenaltyManager`, but I haven't really figured out a good name for that yet.

**Comment by wouterkool** [comment]
I would like to pick this up. I'm fine with calling it `CostEvaluator` (although I think `Objective` would also be fine). This is my proposal:

* C++ CostEvaluator (rename C++ PenaltyManager and remove penalty management methods):
  * Attributes:
    * twPenalty
    * loadPenalty
  * Methods:
    * twPenalty(timewarp)
    * loadPenalty(load, vehicleCapacity) <- make dependency on capacity explicit to support e.g. heterogenous fleet
    * getCost(individual) <- moved from Individual
* C++ Individual:
  * Remove ::cost() and dependency on penalty manager
* C++ SubPopulation:
  * Add setCostEvaluator() function that recomputes biasedFitness
* C++ LocalSearch:
  * Search/intensify take explicit CostEvaluator argument, remove penalty manager dependency
* Python Population:
  * Add set_cost_evaluator that passes it to subpopulations (not, formally only necessary for infeasible subpop)
* Python PenaltyManager (we can change the name later):
  * Methods
    * register_load_feasible(load_feasible: bool) -> bool (to return whether value was updated)
    * register_tw_feasible(load_feasible: bool) -> bool (to return whether value was updated)
    * get_cost_evaluator(booster: bool) -> CostEvaluator
* Python GeneticAlgorithm:
  * Replace booster context manager by ls.search(pm.get_cost_evaluator(booster=True))
  * Change in behavor: add repaired individual to population *outside* of context manager so with non-booster objective!
  * If register_load_feasible or register_tw_feasible returns true, call population.SetCostEvaluator(penalty_manager.get_cost_evaluator())

I am not sure if we still need the PenaltyManager as separate object as we need some logic in GeneticAlgorithm anyway to pass the updated CostEvaluator to Population. Also, the code for time and load penalties is the same, so we could also implement one AutoAdjustingParameter(value, target, increase, decrease) class to use for both.

Code-wise I'm not so happy about passing the updated cost_evaluator to Population everytime it changes, but I think it is better to have this dependency on a changing parameter explicit (e.g. currently we have the weird situation that the booster context temporarily changes the biased fitness definition of the population, which may or may not be updated depending on whether the repaired individual is added to the population).

I think it is worth investigating if we need changing penalties for the population at all or can just keep a default and consider penalty management functionality only for the local search.

@N-Wouda let me know if you have any suggestions, specifically regarding the dependency of SubPopulation on the (changing) CostEvaluator.

**Comment by wouterkool** [comment]
Note: we discussed not using population.set_cost_evaluator(). Instead, we pass in the CostEvaluator everytime we need id (e.g. when calling `select()`), which will then recompute the biased fitness first. This is simple and ensures consistency. We can later speed it up using a caching mechanism.

**Comment by wouterkool** [comment]
> Note: we discussed not using population.set_cost_evaluator(). Instead, we pass in the CostEvaluator everytime we need id (e.g. when calling `select()`), which will then recompute the biased fitness first. This is simple and ensures consistency. We can later speed it up using a caching mechanism.

Update: we need to pass in the `CostEvaluator` when calling `SubPopulation::add()` since that may trigger a purge that requires to compute the biased fitness and hence the cost. It's probably a good idea to still pass it to `select()` as well to recompute the fitness first, but we currently don't do that either. If we do so, we should probably check if it has changed, so we need to store the `CostEvaluator` again, however it is more robust as this is a constant value object.

**Comment by wouterkool** [comment]
@N-Wouda @leonlan to get the discussion in the central place, how about we keep `Individual.cost()` that throws an error if the individual is infeasible, but use `CostEvaluator()` to compute `penalizedCosts` throughout the code.

This would enable us to print the cost for feasible individuals in `Individual::operator<<` and also makes examples easier (no need to get a cost evaluator, we just either print 'infeasible' or the cost).

**Comment by wouterkool** [comment]
Related: the default penalty parameters are now specified in PenaltyParams, however it makes sense to have a default `CostEvaluator` as well. Some ideas:
* Implement a `get_default_cost_evaluator` function that uses the PenaltyParams (doesn't sound great)
* Implement a default constructor that hardcodes the default (I see little value in a `CostEvaluatorParams` object)
  * Then either remove the initial values from PenaltyParams but read these from the default CostEvaluator (this requires making them public)
  * Or let the PenaltyManager have its own, potentially different defaults

Thoughts?

**Comment by N-Wouda** [comment]
I don't want to forget this: any test using `PenaltyManager().get_cost_evaluator()` is somewhat suspect, and should ideally be rewritten to use a `CostEvaluator` directly.

**Comment by wouterkool** [comment]
Agree Default `CostEvaluator` has 0 penalties and `.cost()` which returns infinity if individual is infeasible and `.penalizedCost()` which computes penalized cost. Use `.penalizedCost()` instead of `()` operator everywhere in c++ code.
