### ISSUE TITLE
Move ProblemData.from_file to Python

### ISSUE THREAD

**Issue by leonlan** [N-Wouda/PyVRP#70]
I just released [`vrplib`](https://github.com/leonlan/VRPLIB), so it's a good moment to move `ProblemData.from_file` to the Python side and use `vrplib` to parse the instances.

https://github.com/N-Wouda/pyvrp/blob/7ca863f1893064c69df85fdeecfe9262f8e0407b/pyvrp/read.py#L23

**Comment by N-Wouda** [comment]
I've updated this to reflect that we're going to move the `from_file` method to the Python side. We're not actually getting rid of the `ProblemData` class itself :).

**Comment by wouterkool** [comment]
I'm already using `vrplib` in #62 so I can implement it there. It is a bit unclear how to handle the distance computation/rounding though but I'll propose something for you to review.
