### ISSUE TITLE
Individual == comparison based on neighbours

### ISSUE THREAD

**Issue by wouterkool** [N-Wouda/PyVRP#84]
Implement `Individual::operator==` by comparing `Individual::neighbours` rather than `Individual::routes` which is more robust as it does not depend on the sorting of the routes in the individual

**Comment by N-Wouda** [comment]
Should add a case to `test_eq` in `test_Individual.py` that covers permuted routes (other than empty routes in between, which are always sorted out).

**Comment by N-Wouda** [comment]
I have implemented this in #86, because I needed it for a comparison case in the exchange operator tests.
