### ISSUE TITLE
Use local search intensification at every iteration with some probability

### ISSUE THREAD

**Issue by leonlan** [N-Wouda/PyVRP#98]
The intensification step of local search is currently only applied when a new best solution is found. The original implementation of HGS uses the intensification step at every iteration after the node ops are exhausted. We will try to bring this back to see if we can get better performance.

Related commit from Euro-NeurIPS: https://github.com/N-Wouda/Euro-NeurIPS-2022/commit/1031b8a90742a2756f85f3f415d5189e1fc1fae0

**Comment by wouterkool** [comment]
Note: not every iteration but with a certain `intensificationProbability` intensification should be applied (and probably we should keep it an option to do it as currently, i.e. when a new BKS is found).
